UI/Areas/Admin/Controllers/ProductTemplateController.cs
using Common.Enums;
using DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using UI.Models.ViewModels.FilterModel;
using UI.Models.ViewModels;
using Entities;
using Microsoft.AspNetCore.Identity;


namespace UI.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "admin")]
	public class ProductTemplateController : Controller
	{
		private readonly ILogger<ProductTemplateController> _logger;
		private readonly AppDbContext _context;
		private readonly UserManager<User> _userManager;

		public ProductTemplateController(ILogger<ProductTemplateController> logger, AppDbContext context, UserManager<User> userManager)
		{
			_logger = logger;
			_context = context;
			_userManager = userManager;
		}

		public async Task<IActionResult> Index(ProductTemplateFilterModel filter, int page = 1)
		{
			const int objectsPerPage = 30;
			var startIndex = (page - 1) * objectsPerPage;
			IQueryable<ProductTemplate> source = _context.ProductTemplates
				.Include(item => item.Manufacturer)
				.Include(item => item.Category);
			//source = source.Where(item => item.Active);
			var count = await source.CountAsync();
			var items = await source.Skip(startIndex).Take(objectsPerPage).ToListAsync();

			var viewModel = new SearchResultViewModel<ProductTemplate, ProductTemplateFilterModel>(items, filter, count, startIndex, items.Count, objectsPerPage);
			return View(viewModel);
		}

		public async Task<IActionResult> Update(string id)
		{
			var viewModel = 
				await _context.ProductTemplates.FirstOrDefaultAsync(item => item.VendorCode == id);

			return View(viewModel);
		}
		[HttpPost]
		public async Task<IActionResult> Update(ProductTemplate model)
		{
			if (!ModelState.IsValid)
				return View(model);

			_context.ProductTemplates.Update(model);
			await _context.SaveChangesAsync();

			return RedirectToAction("Index", "Products", new { Area = "Admin" });
		}

		public async Task<IActionResult> Delete(string id)
		{
			try
			{
				var model = await _context.ProductTemplates.FirstOrDefaultAsync(item => item.VendorCode == id);
				model.Active = false;
				_context.ProductTemplates.Update(model);
				await _context.SaveChangesAsync();
			}
			catch (Exception ex)
			{
				_logger.LogError($"{ex}");
			}

			return RedirectToAction("Index", "Products", new { Area = "Admin" });
		}
	}
}

UI/Areas/Admin/Views/ProductTemplate/Index.cshtml
@model SearchResultViewModel<ProductTemplate, ProductTemplateFilterModel>
@{
	ViewBag.CreationLink = Url.Action("Update", "ProductTemplate", new { Area = "Admin" });

	ViewData["Title"] = "Шаблон продукта";

    var pagedList = Html.PagedList(Model.PagesInfo.ItemsCount, Model.PagesInfo.ItemsPerPage, Model.PagesInfo.CurrentPage,
        Model.PagesInfo.DisplayedPages, pageNumber => Url.Action(Url.GetAction(), Model.FilterModel.Merge(new
        {
            page = pageNumber
        })), new PagedListExtensions.PagedListRenderParams());
}

<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table class="table table-striped">
				<tr>

					<th class="text-center">Название</th>
					<th class="text-center">Категория</th>
					<th class="text-center">Производитель</th>
					<th class="text-center">Действия</th>
				</tr>
				@foreach (var item in Model.Objects)
				{
					<tr class="text-center">
						<td>
							@item.Name
						</td>
						<td>
							@item.Category?.Name
						</td>
						<td>
							@item.Manufacturer?.Name
						</td>
						<td class="text-center">
							<a asp-action="Update" asp-area="Admin" asp-route-id="@item.VendorCode">Изменить</a><br />
							<a asp-action="Delete" asp-area="Admin" asp-route-id="@item.VendorCode" class="delete-object-button">Удалить</a>
						</td>
					</tr>
				}
			</table>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		@pagedList
	</div>
</div>

@section Scripts
{

}

UI/Areas/Admin/Views/ProductTemplate/Update.cshtml
@model ProductTemplate
@{
	var exists = Model != null && Model.VendorCode != null;
	ViewBag.Title = (exists ? "Редактирование" : "Создание") + " категории";
}

<form asp-area="Admin" asp-controller="ProductTemplate" asp-action="Update" method="post">
@*	<div class="row">
		<input type="hidden" asp-for="Id" />
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="Name"></label>
				<input type="text" asp-for="Name" class="form-control" autocomplete="off" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
		</div>
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="Alias"></label>
				<input type="text" asp-for="Alias" class="form-control" disabled autocomplete="off" />
				<span asp-validation-for="Alias" class="text-danger"></span>
			</div>
		</div>
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="Amount"></label>
				<input type="text" asp-for="Amount" class="form-control" autocomplete="off" />
				<span asp-validation-for="Amount" class="text-danger"></span>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="UrlImage"></label>
				<input type="text" asp-for="UrlImage" class="form-control" autocomplete="off" />
				<span asp-validation-for="UrlImage" class="text-danger"></span>
			</div>
		</div>
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="Description"></label>
				<input type="text" asp-for="Description" class="form-control" autocomplete="off" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
		</div>
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="Active"></label>
				<input type="checkbox" asp-for="Active" class="form-control" />
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="ManufacturerType"></label>
				<select asp-for="ManufacturerType" class="form-control" asp-items="manufactureType"></select>
				<span asp-validation-for="ManufacturerType" class="text-danger"></span>
			</div>
		</div>
		<div class="col-md-4 col-sm-6">
			<div class="form-group">
				<label asp-for="VendorCode"></label>
				<input type="text" asp-for="VendorCode" class="form-control" autocomplete="off" />
				<span asp-validation-for="VendorCode" class="text-danger"></span>
			</div>
		</div>
	</div>*@
	<div class="row">
		<div class="mx-auto mt-3">
			<button type="submit" class="btn btn-primary">@(exists ? "Сохранить" : "Добавить")</button>
			<a asp-action="Index" class="btn btn-outline-secondary">Отмена</a>
		</div>
	</div>
</form>